=== SzymonCywinski/rowery/rowery.dtd
<?xml version='1.0' encoding='iso-8859-2' ?>
<!-- 
  $Id: rowery.dtd,v 1.1 2007/01/02 12:02:00 tomek Exp $ 
  ..
  .. (c) t. przechlewski, 2004,2005 (tomasz@gnu.univ.gda.pl)
  .. Zezwala sie na wykorzystanie na warunkach licencji 
  .. GPL. patrz: http://www.gnu.org/licenses/gpl.html         
  -->


<!ELEMENT year  ((month | comment)+ )                      >
<!ELEMENT month (day | comment)*                           >
<!ELEMENT day   (ride*, comment? )                         >
<!ELEMENT ride  (by*, comment?   )                         >
<!ELEMENT by EMPTY                                         >
<!ELEMENT comment (#PCDATA)                                >

<!-- dystans ogó³em w zaokr±gleniu w dó³ do 5 km,
        dystans dok³adnie oraz czas:                     -->
<!ENTITY % coreattrs " 
    dist CDATA #IMPLIED
    exdist CDATA #IMPLIED
    time CDATA #IMPLIED "                                  >

<!ATTLIST year no CDATA     #REQUIRED                      >
<!ATTLIST year bike CDATA   #IMPLIED                       >
<!ATTLIST month no CDATA     #REQUIRED                     >

<!-- waga rowerzysty o godz 8.00:                        -->
<!ATTLIST day w8   CDATA     #IMPLIED                      >
<!-- wspolczynnik  zz                                    -->
<!ATTLIST day zz   CDATA     #IMPLIED                      >

<!-- temp. powietrza -->
<!ATTLIST day temp CDATA     #IMPLIED                      >
<!ATTLIST day date CDATA     #REQUIRED                     >
<!-- opis daty ¿e ¶wiêto na przyk³ad                     -->
<!ATTLIST day xdate CDATA    #IMPLIED                      >

<!ATTLIST ride %coreattrs; 
   kml CDATA #IMPLIED
   gpx CDATA #IMPLIED                                      >

<!-- ¶rednia, zwykle liczona na krótszym 
 dystansie ni¿ dist:                                     -->
<!ATTLIST ride mean CDATA   #IMPLIED                       >

<!ATTLIST ride maxspeed CDATA #IMPLIED                     >
<!-- bike: je¿eli bike='g' lub bike='mtb' jazda w terenie-->
<!ATTLIST ride bike CDATA   #IMPLIED                       >

<!-- je¿eli typ=w, wy¶cig; typ=s, sparing                -->
<!ATTLIST ride typ  CDATA   #IMPLIED                       >

<!-- id trasy -->
<!ATTLIST ride id   CDATA   #IMPLIED                       >

<!-- dwuliterowy kod kraju; domy¶lnie PL                 -->
<!ATTLIST by country CDATA    "pl"                         >
<!ATTLIST by name CDATA       #IMPLIED                     >
<!ATTLIST by %coreattrs;                                   >

<!ATTLIST comment date CDATA #IMPLIED                      >

<!-- koniec -->

=== SzymonCywinski/rowery/c2020.xml
<?xml version='1.0' encoding='utf-8' standalone='no' ?>
<!DOCTYPE year SYSTEM "rowery.dtd" >

<year no="2020" done='242355'>
   <month no="1">

     <day date="2020/01/07">
       <ride dist="40" exdist="40.00" bike='cx' gpx='20200107'>
	 <by name='Warzenko'/>
       </ride>
     </day>
     
     <day date="2020/01/08">
       <ride dist="45" exdist="44.00" bike='cx' gpx='20200108'>
	 <by name='Wiczlino'/>
       </ride>
     </day>
     
     <day date="2020/01/09">
       <ride dist="40" exdist="43.00" bike='cx' gpx='20200109'>
	 <by name='Banino'/>
	 <by name='Miszewo'/>
       </ride>
     </day>

     <day date="2020/01/11">
       <ride dist="75" exdist="74.80" bike='cx' gpx='20200111'>
	 <by name='Gdańsk'/>
	 <by name='Świbno'/>
       </ride>
     </day>
     <day date="2020/01/13">
       <ride dist="60" exdist="60.80" bike='cx' gpx='20200113'>
	 <by name='Gdańsk'/>
	 <by name='Sobieszewo'/>
       </ride>
     </day>

     <day date="2020/01/14">
       <ride dist="45" exdist="44.00" bike='cx' gpx='20200114'>
	 <by name='Koleczkowo'/>
	 <by name='Wiczlino'/>
       </ride>
     </day>

     <day date="2020/01/15">
       <ride dist="40" exdist="41.80" bike='ridley' gpx='20200115'>
	 <by name='Gdynia'/>
	 <by name='Koleczkowo'/>
       </ride>
     </day>

     <day date="2020/01/16">
       <ride dist="40" exdist="39.80" bike='cx' gpx='20200116'>
	 <by name='Gdańsk'/>
	 <by name='Rębiechowo'/>
       </ride>
     </day>
     <day date="2020/01/17">
       <ride dist="55" exdist="54.10" bike='cx' gpx='20200117'>
	 <by name='Kamień'/>
	 <by name='Koleczkowo'/>
       </ride>
     </day>

     <day date="2020/01/19">
       <ride dist="55" exdist="56.10" bike='cx' gpx='20200119'>
	 <by name='Gdynia'/>
	 <by name='Rewa'/>
       </ride>
     </day>
     
     <day date="2020/01/20">
       <ride dist="35" exdist="37.10" bike='cx' gpx='20200120'>
	 <by name='Gdańsk'/>
	 <by name='Rębiechowo'/>
	 <by name='Barniewice'/>
       </ride>
     </day>
     
     <day date="2020/01/21">
       <ride dist="35" exdist="36.10" bike='cx' gpx='20200121'>
	 <by name='Gdańsk'/>
	 <by name='Osowa'/>
       </ride>
     </day>
     <day date="2020/01/22">
       <ride dist="55" exdist="56.10" bike='cx' gpx='20200122'>
	 <by name='Gdańsk'/>
	 <by name='Sobieszewo'/>
       </ride>
     </day>
     <day date="2020/01/23">
       <ride dist="40" exdist="39.75" bike='cx' gpx='20200123'>
	 <by name='Chwaszczyno'/>
	 <by name='Warzenko'/>
       </ride>
     </day>
     
     <day date="2020/01/24">
       <ride dist="55" exdist="54.10" bike='cx' gpx='20200124'>
	 <by name='Gdańsk'/>
	 <by name='Warzenko'/>
       </ride>
     </day>
     
     <day date="2020/01/26">
       <ride dist="105" exdist="108.10" bike='ridley' gpx='20200126'>
	 <by name='Majewo'/>
	 <by name='Kwidzyn'/>
 	 <by name='Piekło'/>
	 <by name='Tczew'/>
	 <by name='Pruszcz Gdański'/>
	 <by name='Gdańsk'/>
       </ride>
     </day>

     <day date="2020/01/27">
       <ride dist="45" exdist="44.10" bike='ridley' gpx='20200127'>
	 <by name='Banino'/>
	 <by name='Miszewo'/>
       </ride>
     </day>
     <day date="2020/01/28">
       <ride dist="45" exdist="44.10" bike='cx' gpx='20200128'>
	 <by name='Banino'/>
	 <by name='Miszewo'/>
       </ride>
     </day>
     <day date="2020/01/29">
       <ride dist="25" exdist="24.10" bike='cx' gpx='20200129'>
	 <by name='Gdańsk'/>
       </ride>
     </day>
     <day date="2020/01/30">
       <ride dist="45" exdist="45.10" bike='cx' gpx='20200130'>
	 <by name='Kielno'/>
	 <by name='Koleczkowo'/>
       </ride>
     </day>

     <day date="2020/01/31">
       <ride dist="25" exdist="24.90" bike='cx' gpx='20200131'>
	 <by name='Gdańsk'/>
       </ride>
     </day>
   </month>
   
   <month no='2'>
     <day date="2020/02/01">
       <ride dist="60" exdist="62.02" bike='cx' gpx='20200201'>
	 <by name='Gdańsk'/>
       </ride>
     </day>
     
   </month>
</year>
